# OpenManus-BugHunting Configuration for DeepSeek API
[llm]
model = "deepseek-chat"
base_url = "https://api.deepseek.com/v1"
api_key = ""
max_tokens = 4096
temperature = 0.3
api_type = "openai"
api_version = "v1"

[llm.default]
model = "deepseek-chat"
base_url = "https://api.deepseek.com/v1"
api_key = ""
max_tokens = 4096
temperature = 0.3
api_type = "openai"
api_version = "v1"