# DeepSeek LLM configuration for OpenManus-BugHunting
[llm]
model = "deepseek-chat"
base_url = "https://api.deepseek.com/v1"
api_key = "your-api-key-here"
max_tokens = 4096
temperature = 0.3
api_type = "openai"
api_version = "v1"

# Default configuration for AI tool selection
[llm.default]
model = "deepseek-chat"
base_url = "https://api.deepseek.com/v1"
api_key = "your-api-key-here"
max_tokens = 4096
temperature = 0.3
api_type = "openai"
api_version = "v1"
