# DeepSeek Configuration for OpenManus-BugHunting
# Copy this file to config.toml and update with your API key

[llm.deepseek]
model = "deepseek-chat"
base_url = "https://api.deepseek.com"
api_key = "YOUR_DEEPSEEK_API_KEY_HERE"
max_tokens = 4096
max_input_tokens = 100000
temperature = 0.7
api_type = "deepseek"
api_version = "v1"

# Alternative models you can use:
# model = "deepseek-coder"     # For coding tasks
# model = "deepseek-reasoner"  # For reasoning tasks

[search]
engine = "Google"
fallback_engines = ["DuckDuckGo", "Baidu", "Bing"]
retry_delay = 60
max_retries = 3
lang = "en"
country = "us"

[browser]
headless = false
disable_security = true
max_content_length = 2000

[sandbox]
use_sandbox = false
image = "python:3.12-slim"
work_dir = "/workspace"
memory_limit = "512m"
cpu_limit = 1.0
timeout = 300
network_enabled = false